{% set version = '0.4-11.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recordlinkage
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RecordLinkage_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RecordLinkage/RecordLinkage_{{ version }}.tar.gz
  sha256: 13048a4bb15a2a95c62bda732434959bc8367e2e275ad1e62e2e53010fe2abac

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dbi
    - r-rsqlite >=1.0.0
    - r-ada
    - r-data.table >=1.7.8
    - r-e1071
    - r-evd
    - r-ff
    - r-ffbase
    - r-ipred
    - r-nnet
    - r-rpart
    - r-xtable
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-dbi
    - r-rsqlite >=1.0.0
    - r-ada
    - r-data.table >=1.7.8
    - r-e1071
    - r-evd
    - r-ff
    - r-ffbase
    - r-ipred
    - r-nnet
    - r-rpart
    - r-xtable

test:
  commands:
    - $R -e "library('RecordLinkage')"           # [not win]
    - "\"%R%\" -e \"library('RecordLinkage')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/recordlinkage/, https://journal.r-project.org/archive/2010-2/RJournal_2010-2_Sariyar+Borg.pdf
  license: GPL (>= 2)
  summary: 'Provides functions for linking and de-duplicating data sets. Methods based on a stochastic
    approach are implemented as well as  classification algorithms from the machine
    learning domain. '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RecordLinkage
# Version: 0.4-11.1
# Title: Record Linkage in R
# Author: Andreas Borg <andreas.borg.public@posteo.de>, Murat Sariyar <murat.sariyar@charite.de>
# Maintainer: ORPHANED
# Contact: andreas.borg.public@posteo.de
# Description: Provides functions for linking and de-duplicating data sets. Methods based on a stochastic approach are implemented as well as  classification algorithms from the machine learning domain.
# License: GPL (>= 2)
# Depends: R (>= 2.10.0), DBI, RSQLite(>= 1.0.0), ff, ffbase
# Imports: e1071, rpart, ada, ipred, stats, evd, methods, data.table (>= 1.7.8), nnet, xtable
# Suggests: RUnit
# URL: https://r-forge.r-project.org/projects/recordlinkage/, https://journal.r-project.org/archive/2010-2/RJournal_2010-2_Sariyar+Borg.pdf
# Collate: register-S3-classes.r RLBigData-classes.r RLResult-class.r accessor-methods.r evt.r classify.r classifySupv-methods.r genSamples.r strcmp.r compare.r getPairs.r summary.r em-methods.r internals.r em.r mygllm.r epilink-methods.r phonetics.r onAttach.r getPairs-methods.r serialization.r tools.r stochastic.r
# NeedsCompilation: yes
# Packaged: 2019-05-28 08:31:33 UTC; ripley
# Repository: CRAN
# Date/Publication: 2019-05-28 09:45:05 UTC
# X-CRAN-Original-Maintainer: Andreas Borg <andreas.borg.public@posteo.de>
# X-CRAN-Comment: Orphaned and updated for R 3.6.0 on 2019-05-28 despite reminders/
