{% set version = "0.4-12.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recordlinkage
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RecordLinkage_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RecordLinkage/RecordLinkage_{{ version }}.tar.gz
  sha256: 73bd4f1af768be8786153afc28c6f4162d2a6f0bc053d8d0e1c1b197a6d6d149

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ada
    - r-data.table >=1.7.8
    - r-dbi
    - r-e1071
    - r-evd
    - r-ff
    - r-ipred
    - r-nnet
    - r-rpart
    - r-rsqlite >=1.0.0
    - r-xtable
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-ada
    - r-data.table >=1.7.8
    - r-dbi
    - r-e1071
    - r-evd
    - r-ff
    - r-ipred
    - r-nnet
    - r-rpart
    - r-rsqlite >=1.0.0
    - r-xtable

test:
  commands:
    - $R -e "library('RecordLinkage')"           # [not win]
    - "\"%R%\" -e \"library('RecordLinkage')\""  # [win]

about:
  home: https://cran.r-project.org/package=RecordLinkage
  license: GPL-2.0-or-later
  summary: Provides functions for linking and de-duplicating data sets. Methods based on a stochastic approach are implemented as well as classification algorithms from the machine learning domain.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
