{% set version = "0.4-12.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-recordlinkage
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RecordLinkage_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RecordLinkage/RecordLinkage_{{ version }}.tar.gz
  sha256: 3db03e2fd8c6a34cc5390065dc1ea30f7b11b505b26f128e14facfeaa7e5b791

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dbi
    - r-rsqlite >=1.0.0
    - r-ada
    - r-data.table >=1.7.8
    - r-e1071
    - r-evd
    - r-ff
    - r-ipred
    - r-nnet
    - r-rpart
    - r-xtable
  run:
    - r-base
    - r-dbi
    - r-rsqlite >=1.0.0
    - r-ada
    - r-data.table >=1.7.8
    - r-e1071
    - r-evd
    - r-ff
    - r-ipred
    - r-nnet
    - r-rpart
    - r-xtable

test:
  commands:
    - $R -e "library('RecordLinkage')"           # [not win]
    - "\"%R%\" -e \"library('RecordLinkage')\""  # [win]

about:
  home: https://cran.r-project.org/package=RecordLinkage
  license: GPL-2.0-or-later
  summary: 'Provides functions for linking and deduplicating data sets. Methods based on a stochastic
    approach are implemented as well as classification algorithms from the machine learning
    domain. For details, see our paper "The RecordLinkage Package: Detecting Errors
    in Data" Sariyar M / Borg A (2010) <doi:10.32614/RJ-2010-017>.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
