appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: H7WQqnqKORKyreLH4R/VAPHk8G1zhPUy+5EKXFLxembhOPjNbFzmxmyjTEaSF4cp4DOa19cq1+p0j9vwXA98lu9aYuZRDlnDwEqcsAxwoTcZBIba4xd5+2RHFAZF0mTIvk9ocDQ2YsaAlnaKjqJA/9w9yG2ssTSYu7Np5ItaSqygZ7ZBv2KnXAQ7+cNXODLNUNxXDAJUFS+qW5gFmzMH57tb72d2KwmMkMiWC2U1rV7l6AmQzi9KFjRWE7PsYsEbag3l7on3drjRMRilLmH+5ksxURyxXkWCy6a+3C0FH46biushxxrwS7ubLP3vmJi1m/brQsU3oLQCQX8fIuS8l/IvWU2ufLbHssVJ/nvdsmlhzYREYWhk/tpo8eb3gmCEn/Sm2jR1BGeL4ZgZxyi6uIjMRkEapRAjrmqIERt15kfBzunXiDoZTHNKHenrTg2ldkwo4CwbBO4zoB8AJoZCTwosbJMh0aKSfC7OAZ/jdGbt+6TjlHhTWEAs8+SkkRXLMLsT1L+MZzsZvPn0Q7gm38Sd43fgikyMAscTcwWzp5P/IK8vkQg7v7Z2zJaziVUrPcuBZ4mbHfGuRRF6VfV3oyamFjhTHCPP3DvCCDsctqC4iQ8A283EZAuGnd7938f3mO587HFkoepKK+eMKTTsJ4/x2O2S/dOrFiSBbEX6xF4=
